env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard
  - prettier
overrides:
  - files:
      - "*.ts"
      - "*.tsx"
    parser: "@typescript-eslint/parser"
    plugins:
      - "@typescript-eslint"
      - testing-library
    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
  - files:
      - "spec/**/*.ts"
    plugins:
      - jest
    extends:
      - plugin:jest/recommended
    rules: {
      'testing-library/await-async-query': 'error',
		  'testing-library/no-await-sync-query': 'error',
		  'testing-library/no-debugging-utils': 'warn',
		  'testing-library/no-dom-import': 'off',
    }
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {}
settings:
  react:
    version: detect
