env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard
  - prettier
overrides:
  - files:
    - "*.ts"
    - "*.tsx"
    parser: "@typescript-eslint/parser"
    plugins:
      - "@typescript-eslint"
    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {}
settings:
  react:
    version: detect
