name: ci action
description: unit tests

runs:
  using: composite
  steps:
    - name: Check out source code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.3'

    - name: Install dependencies
      run: bundle install
      shell: bash

    - name: Run lint
      run: rubocop
      shell: bash

    - name: Run tests
      run: bundle exec rspec
      shell: bash
