runs:
  using: "Composite"
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.3'
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rspec
