runs:
  using: "Composite"
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.3'
      shell: bash
      
    - name: Install dependencies
      run: bundle install
      shell: bash

    - name: Run tests
      run: bundle exec rspec
      shell: bash
