name: ci

on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1.3
      env:
        RAILS_ENV: test
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Trigger ci action
        uses: ./.github/actions/ci
