name: ci

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
